INFO:root:train size: 20, test size: 343
INFO:root:X_test_noise shape: (343, 24)
2022-12-22 14:29:33,639	INFO worker.py:1518 -- Started a local Ray instance.
[36m(partial_opw pid=13123)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: divide by zero encountered in true_divide
[36m(partial_opw pid=13123)[39m   u = 1. / nx.dot(Kp, v)
[36m(partial_opw pid=13123)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:492: UserWarning: Warning: numerical errors at iteration 0
[36m(partial_opw pid=13123)[39m   warnings.warn('Warning: numerical errors at iteration %d' % ii)
[36m(partial_opw pid=13123)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: overflow encountered in true_divide
[36m(partial_opw pid=13123)[39m   u = 1. / nx.dot(Kp, v)
[36m(partial_opw pid=13125)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: divide by zero encountered in true_divide
[36m(partial_opw pid=13125)[39m   u = 1. / nx.dot(Kp, v)
[36m(partial_opw pid=13125)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:492: UserWarning: Warning: numerical errors at iteration 0
[36m(partial_opw pid=13125)[39m   warnings.warn('Warning: numerical errors at iteration %d' % ii)
[36m(partial_opw pid=13126)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: divide by zero encountered in true_divide
[36m(partial_opw pid=13126)[39m   u = 1. / nx.dot(Kp, v)
[36m(partial_opw pid=13126)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:492: UserWarning: Warning: numerical errors at iteration 0
[36m(partial_opw pid=13126)[39m   warnings.warn('Warning: numerical errors at iteration %d' % ii)
[36m(partial_opw pid=13124)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: divide by zero encountered in true_divide
[36m(partial_opw pid=13124)[39m   u = 1. / nx.dot(Kp, v)
[36m(partial_opw pid=13124)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:492: UserWarning: Warning: numerical errors at iteration 0
[36m(partial_opw pid=13124)[39m   warnings.warn('Warning: numerical errors at iteration %d' % ii)
[36m(partial_opw pid=13124)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: overflow encountered in true_divide
[36m(partial_opw pid=13124)[39m   u = 1. / nx.dot(Kp, v)
[36m(partial_opw pid=13125)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: overflow encountered in true_divide
[36m(partial_opw pid=13125)[39m   u = 1. / nx.dot(Kp, v)
[36m(partial_opw pid=13126)[39m /home/phu/.local/lib/python3.10/site-packages/ot/bregman.py:485: RuntimeWarning: overflow encountered in true_divide
[36m(partial_opw pid=13126)[39m   u = 1. / nx.dot(Kp, v)


100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 6860/6860 [00:03<00:00, 1788.38it/s]
INFO:root:Accuracy: 0.7317784256559767
INFO:root:cost time: 8.254932880401611